core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
]

hejab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('products/', include('products.urls')),
    path('subscribe/', include('subscribe.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('index', views.products, name='products'),
    path('favorite/', views.favorite, name='favorite'),
    path('shopping-cart/', views.shopping, name='shopping-cart')
]

subscribe/urls.py
from django.urls import path

from . import views


app_name = 'subscribe'
urlpatterns = [
    path('', views.subscribe, name='subscribe'),
    path('success', views.success, name="success"),
    path('error', views.error, name="error"),
    path('unsubscribe', views.unsubscribe, name="unsubscribe"),
]

core/models.py
from django.db import models


class Core(models.Model):
    title = models.CharField('عنوان وب سایت', max_length=200)
    desc = models.CharField('توضیح کوتاه', max_length=200)
    address = models.TextField('آدرس', blank=True)

    about = models.TextField('درباره ما')
    contact = models.TextField('تماس با ما')

    location = models.TextField('آدرس نقشه گوگل', help_text='در صورت داشتن مکان فیزیکی می توانید آدرس گوگل خود را وارد نمایید', blank=True)

    class Meta:
        verbose_name = 'اطلاعات وب سایت'
        verbose_name_plural = 'مشخصات وب سایت'

    def __str__(self):
        return self.title

products/models.py
from django.db import models

# Create your models here.

subscribe/models.py
from django.db import models
from django.utils import timezone


class Subscribe(models.Model):
    email = models.EmailField('پست الکترونیک')
    created_at = models.DateTimeField('تاریخ ثبت', default=timezone.now)

    class Meta:
        verbose_name = 'عضو خبرنامه'
        verbose_name_plural = 'اعضا خبرنامه'
    
    def __str__(self):
        return self.email

core/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField('موضوع', max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=false)

subscribe/forms.py
from django import forms

class SubscribeForms(forms.Form):
    email = forms.EmailField(label='پست الکترونیک', max_length=100)

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


def index(request):

    return render(request, 'core/index.html')


def about(request):

    return render(request, 'core/about.html')


def contact(request):
    
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('core:index')
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }
    
    return render(request, 'registration/signup.html', context)

products/views.py
from django.shortcuts import render


def products(request):

    return render(request, 'products/products.html')


def product(request):

    return render(request, 'products/product.html')


def favorite(request):
    
    return render(request, 'products/favorite.html')


def shopping(request):

    return render(request, 'products/shopping-cart.html')

subscribe/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import SubscribeForms
from .models import Subscribe


def subscribe(request):
    registered = Subscribe.objects.all()

    if request.method == 'POST':
        form = SubscribeForms(request.POST)

        if form.is_valid:
            subscribe = Subscribe(email=request.POST['email'])

            if Subscribe.objects.filter(email=subscribe):
                return HttpResponseRedirect(reverse('subscribe:error'))

            else:
                subscribe.save()
                return HttpResponseRedirect(reverse('subscribe:success'))

    else:
        form = SubscribeForms()

    return render(request, 'subscribe/subscribe.html', {'form': form})


def success(request):

    return render(request, 'subscribe/success.html')


def error(request):
    
    return render(request, 'subscribe/error.html')


def unsubscribe(request):
    pass

templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="fa">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'icon/icon.ico' %}" title="favicon">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <!-- Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <!-- Lightbox2 -->
    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
    
    <!-- Owl Carousel 2 -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>فروشگاه آنلاین {{ core|default:'آرنیکا' }}</title>
</head>
<body>
    
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}
    
    
    <!-- Carousel -->
    {% include 'partials/_carousel.html' %}
    
    <!-- Container -->
    <div class="container mb-3 p-2">
        
        <!-- User Status -->
        {% include 'partials/_user_status.html' %}
        
        <!-- Content -->
        {% block content %}{% endblock %}
        
    </div>
    
    <!-- Footer -->
    {% include 'partials/_footer.html' %}
    
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    
    <!-- Font Awesome -->
    <script src="{% static 'js/all.js' %}"></script>
    
    <!-- WOW -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script>
        new WOW().init();
    </script>
    
    <!-- Lightbox 2 -->
    <script src="{% static 'js/lightbox.js' %}"></script>
    
    <!-- Owl Carousel 2 -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    
    <!-- Custom JS -->
    <script src="{% static 'js/custom.js' %}"></script>
    
    <!-- Live Icons -->
    <script src="{% static 'js/raphael-min.js' %}"></script>
    <script src="{% static 'js/livicons.js' %}"></script>
</body>
</html>

templates/core/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="card mb-3"">
    <div class="row no-gutters">
        
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">درباره ما</h5>
                <h6 class="card-subtitle mb-3 text-muted">{{ core.desc }}</h6>
                <p class="card-text mb-3 justify">
                    {{ core.about|linebreaksbr }}
                </p>
                <p class="card-text"><small class="text-muted">با تشکر از حسن انتخاب شما</small></p>
            </div>
        </div>
        
        <div class="col-md-4 p-3">
            <img src="{% static 'images/about.jpg' %}" class="card-img" alt="درباره ما">
        </div>
        
    </div>
</div>

{% endblock %}

templates/core/contact.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-5">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-3">تماس با ما</h5>
                <p class="card-text justify">
                    {{ core.contact|linebreaksbr }}
                </p>
                <hr>
                <h5 class="card-title mb-3">ما را دنبال کنید</h5>
                <div class="d-flex justify-content-around">
                    <a href="https://telegram.org/" target="_blank"><span class="fab fa-telegram social" title="کانال تلگرام" style="color: #0088cc;"></span></a>
                    <a href="https://www.instagram.com/" target="_blank"><span class="fab fa-instagram social" title="صفحه اینستاگرام" style="color: #f77737;"></span></a>
                    <a href="https://www.facebook.com/" target="_blank"><span class="fab fa-facebook social" title="صفحه فیسبوک" style="color: #3b5998"></span></a>
                    <a href="https://www.youtube.com/" target="_blank"><span class="fab fa-youtube social" title="کانال یوتیوب" style="color: #ff0000"></span></a>
                </div>
            </div>
            
            
        </div>
        
        
    </div>
    
    <div class="col-md-1"></div>
    
    <div class="col-md-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-3">فرم تماس با ما</h5>
                <form>
                    <div class="form-group">
                        <label for="inputName">نام و نام خانوادگی</label>
                        <input type="text" class="form-control" id="inputName" aria-describedby="nameHelp" placeholder="">
                        <small id="nameHelp" class="form-text text-muted">جهت ارتباط بهتر نام و نام خانوادگی خود را وارد نمایید</small>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail">آدرس پست الکترونیک</label>
                        <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="" style="text-align: left">
                        <small id="emailHelp" class="form-text text-muted">پست الکترونیک شما هرگز منتشر نخواهد شد</small>
                    </div>
                    <div class="form-group">
                        <label for="inputSubject">موضوع پیام</label>
                        <input type="text" class="form-control" id="inputSubject" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="imputText">متن پیام</label>
                        <textarea class="form-control" id="inputText" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-12">
        <!-- Google Map -->
        <div class="card border-0 mb-3">
            <div class="card-body p-0">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6517.200771896563!2d60.626797185446414!3d35.24131656158083!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f15b5cfc0dfcb51%3A0xda19793add4f0c81!2z2LTYsdqp2Kog2KrZiNmE24zYr9uMINit2KzYp9ioINmE2KfZhNmH!5e0!3m2!1sfa!2s!4v1567006884131!5m2!1sfa!2s" width="100%" height="300" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/core/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Special Products 3 Items-->
<div class="card-deck mx-0 mb-5 py-1">
    
    <!-- First Item -->
    <div class="card wow fadeInRight">
        <a href="{% static 'images/product-01.jpg' %}" data-lightbox="product-01">
            <img src="{% static 'images/product-01.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">چادر</h4>
            <p class="card-text my-3">تولید انواع چادر با پارچه انحصاری</p>
        </div>
    </div>
    
    <!-- Second Item -->
    <div class="card wow fadeInUp">
        <a href="{% static 'images/product-02.jpg' %}" data-lightbox="product-02">
            <img src="{% static 'images/product-02.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">مانتو شال</h4>
            <p class="card-text my-3">تولید انواع مانتو شال با پارچه انحصاری</p>
        </div>
    </div>
    
    <!-- Third Item -->
    <div class="card wow fadeInLeft">
        <a href="{% static 'images/product-03.jpg' %}" data-lightbox="product-03">
            <img src="{% static 'images/product-03.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">مقنعه</h4>
            <p class="card-text my-3">تولید انواع مقنعه با پارچه انحصاری</p>
        </div>
    </div>
    
</div>

<!-- Special Products 4 Items -->
<div class="card-deck mx-0 mb-5 py-1">
    
    <!-- Item -->
    <div class="card wow fadeInUp">
        <a href="{% static 'images/product-04.jpg' %}" data-lightbox="product-04">
            <img src="{% static 'images/product-04.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">هد بند</h4>
            <p class="card-text my-3">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
        </div>
    </div>
    
    <!-- Item -->
    <div class="card wow fadeInUp">
        <a href="{% static 'images/product-05.jpg' %}" data-lightbox="product-05">
            <img src="{% static 'images/product-05.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">ساق دست</h4>
            <p class="card-text my-3">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
        </div>
    </div>
    
    <!-- Item -->
    <div class="card wow fadeInUp">
        <a href="{% static 'images/product-06.jpg' %}" data-lightbox="product-06">
            <img src="{% static 'images/product-06.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">دستکش</h4>
            <p class="card-text my-3">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
        </div>
    </div>
    
    <!-- Item -->
    <div class="card wow fadeInUp">
        <a href="{% static 'images/product-07.jpg' %}" data-lightbox="product-07">
            <img src="{% static 'images/product-07.jpg' %}" class="card-img-top c-mouse" alt="">
        </a>
        <div class="card-body text-center">
            <h4 class="card-title">جوراب</h4>
            <p class="card-text my-3">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
        </div>
    </div>
    
</div>

<!-- Jumbotron -->   
<div class="jumbotron wow zoomIn">
    <h1 class="display-5">شرکت تولیدی و فروشگاه حجاب لاله</h1>
    <hr class="my-4">
    <p class="lead justify">
        ما توانسته ایم علاوه بر گردآوری تمامی محصولات حجاب از برندهای معتبر تولیدی حجاب
        در کشور و فروش محصولات آنها به قیمت درب کارخانه و تولیدات متنوع دیگر برای 
        هر چه آسانتر کردن خرید تمامی ملزومات حجاب برای شما عزیزان.
    </p>    
</div>

<!-- New Recived Products Title -->
<div class="mb-3">
    <h2 class="text-center">جدیدترین محصولات</h2>
</div>

<!-- New Recived Products Items -->
<div class="owl-carousel mb-5">
    
    <div class="card border-0">
        <img src="{% static 'images/product-01.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
    <div class="card border-0">
        <img src="{% static 'images/product-02.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
    <div class="card border-0">
        <img src="{% static 'images/product-03.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
    <div class="card border-0">
        <img src="{% static 'images/product-04.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
    <div class="card border-0">
        <img src="{% static 'images/product-05.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
    <div class="card border-0">
        <img src="{% static 'images/product-06.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
    <div class="card border-0">
        <img src="{% static 'images/product-07.jpg' %}" class="card-img-top rounded" alt="">
        <div class="card-body text-center">
            <h4 class="card-title">لورم ایپسوم</h4>
        </div>
    </div>
    
</div>

<!-- Brands Title -->
<div class="mb-3">
    <h2 class="text-center">برندها</h2>
</div>

<!-- Brands Itmes -->
<div class="d-flex flex-wrap-reverse justify-content-around mb-5 py-2">
    <div>
        <img src="{% static 'images/brand-lale.jpg' %}" class="brand" alt="">
    </div>
    <div>
        <img src="{% static 'images/brand-sana.jpg' %}" class="brand" alt="">
    </div>
</div>

{% endblock %}

templates/partials/_footer.html
<footer class="bg-dark text-light">
    
    <div class="card-deck m-3 py-3">
        <div class="card bg-dark text-light">
            <div class="card-body">
                <h5 class="card-title mb-3">حجاب لاله</h5>
                <p class="card-text justify">
                    اعتقاد داریم توانسته ایم بهترین محصولات حجاب را با نازلترین قیمت برای شما هموطنان گرامی فراهم کنیم.
                </p>
            </div>
        </div>
        
        <div class="card bg-dark text-light">
            <div class="card-body">
                <h5 class="card-title mb-3">دسترسی سریع</h5>
                <p class="card-text">
                    <ul class="list-unstyled">
                        <li><a href="{% url 'core:about' %}" class="text-light">درباره ما</a></li>
                        <li><a href="{% url 'core:contact' %}" class="text-light">تماس با ما</a></li>
                        <li><a href="{% url 'products:products' %}" class="text-light">محصولات</a></li>
                        <li><a href="{% url 'products:favorite' %}" class="text-light">علاقه مندی</a></li>
                        <li><a href="{% url 'products:shopping-cart' %}" class="text-light">سبد خرید</a></li>
                    </ul>
                </p>
            </div>
        </div>
        
        <div class="card bg-dark text-light">
            <div class="card-body">
                <h5 class="card-title mb-3">محصولات</h5>
                <p class="card-text">
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">چادر ۲۰</span></a>
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">مانتوشال ۱۲</span></a>
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">مقنعه ۳۴</span></a>
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">هدبند ۳۴</span></a>
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">ساق دست ۵۲</span></a>
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">دستکش ۱۲</span></a>
                    <a href=""><span class="badge badge-pill badge-info m-1 p-2">جوراب ۴۵</span></a>
                </p>
            </div>
        </div>
        
        <div class="card bg-dark text-light">
            <div class="card-body">
                <h5 class="card-title mb-3">خبرنامه</h5>
                <p class="card-text justify">
                    جهت اطلاع از تازه ترین محصولات، تخفیف ها و هدایا در خبرنامه عضو شوید.
                </p>
                <div class="text-center mt-3">
                    <a href="{% url 'subscribe:subscribe' %}" class="btn btn-primary">عضویت در خبرنامه</a>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Sub Footer -->
    <div class="border-top border-secondary bg-dark text-light sub-footer">
        <p class="text-center align-middle py-2">
            کلیه حقوق برای فروشگاه آنلاین
            <a href="{% url 'core:index' %}" class="text-decoration-none">{{ core }}</a>
            محفوظ است
            |
            طراحی و برنامه نویسی توسط 
            <a href="" class="text-decoration-none">شرکت توسعه وب آرنیکا</a>
        </p>
    </div>
    
</footer>

templates/partials/_navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light py-0" style="background-color: cornsilk">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse mr-3" id="navbarNavDropdown">
        <ul class="navbar-nav">
            {% if request.path == '/' %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'core:index' %}">خانه <span class="sr-only">(current)</span></a>
            </li>
            {% if 'about' in request.path %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'core:about' %}">درباره</a>
            </li>
            {% if 'contact' in request.path %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'core:contact' %}">تماس</a>
            </li>
            {% if 'products/index' in request.path %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'products:products' %}">محصولات</a>
            </li>
            {% if 'favorite' in request.path %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'products:favorite' %}">علاقه مندی</a>
            </li>
            {% if 'shopping-cart' in request.path %}
            <li class="nav-item active">
            {% else %}
            <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'products:shopping-cart' %}">سبد خرید</a>
            </li>
        </ul>
    </div>
    
    <!-- Left Section -->
    <!-- Button trigger modal -->
    <a href="" class="livicon" data-name="search" data-toggle="modal" data-target="#searchModal"></a>
    
    <a href="{% url 'products:favorite' %}" class="text-decoration-none m-3">
        <span>۰</span>
        <span class="livicon" data-name="heart" data-color="red"></span>
    </a>
    
    <a href="{% url 'products:shopping-cart' %}" class="text-decoration-none">
        <span>۰</span>
        <span class="livicon" data-name="shopping-cart"></span>
    </a>
</nav>

<!-- Modal -->
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="searchModalLabel">جستجوی کالا</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="">
                    <div class="input-group mb-3">
                        <input type="text" name="search" id="search" class="form-control" placeholder="دنبال چی بگردم؟" aria-label="Recipient's username" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">جستجو</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/partials/_user_status.html
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded  mb-3">
    {% if user.is_authenticated %}
    <!-- Logged User -->
    <div class="dropdown">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="loggedUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fas fa-user-alt mr-2"></span>
            {{ user.first_name|default:user.username }} عزیز خوش آمدید
        </button>
        <div class="dropdown-menu" aria-labelledby="loggedUser">
            <a class="dropdown-item" href="{% url 'products:favorite' %}">
                <span class="livicon mr-2" data-name="heart" data-color="red" data-size="24"></span>علاقه مندی ها
            </a>
            <a class="dropdown-item" href="{% url 'products:shopping-cart' %}">
                <span class="livicon mr-2" data-name="shopping-cart" data-size="24"></span>سبد خرید
            </a>
            
            <div class="dropdown-divider"></div>
            
            <a class="dropdown-item disabled" href="#">
                <span class="livicon mr-2" data-name="gift" data-color="red" data-size="24"></span>هدیه
            </a>
            
            <div class="dropdown-divider"></div>
            
            <a class="dropdown-item" href="{% url 'admin:index' %}">
                <span class="livicon mr-2" data-name="dashboard" data-size="24"></span>مدیریت وبگاه
            </a>
            <a class="dropdown-item" href="{% url 'password_change' %}">
                <span class="livicon mr-2" data-name="lock" data-size="24"></span>تغییر گذر واژه
            </a>
            
            <div class="dropdown-divider"></div>
            
            <a class="dropdown-item" href="{% url 'logout' %}">
                <span class="livicon mr-2" data-name="sign-out" data-size="24"></span>خروج
            </a>
        </div>
    </div> 
    {% else %}            
    <!-- Guest User -->
    <div class="dropdown">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="guestUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fas fa-user-alt mr-2"></span>
            مهمان گرامی خوش آمدید
        </button>
        <div class="dropdown-menu" aria-labelledby="guestUser">
            <a class="dropdown-item" href="{% url 'login' %}">
                <span class="livicon mr-2" data-name="sign-in" data-size="24"></span>ورود
            </a>
            <a class="dropdown-item" href="{% url 'core:signup' %}">
                <span class="livicon mr-2" data-name="user-add" data-size="24"></span>ثبت نام
            </a>
        </div>
    </div> 
    {% endif %}
</nav>

templates/products/favorite.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

templates/products/product.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

templates/products/products.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

templates/products/shopping-cart.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

templates/subscribe/error.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">شما مشترک هستید!</h4>
            <hr>
            <p>از اینکه در خبرنامه عضو شدید سپاسگذاریم. ما شما را همچنان در جریان جدیدترین محصولات، قیمت ها و رویدادها قرار خواهیم داد.</p>
        </div>
    </div>  
</div>  

{% endblock %}